import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from './footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Portfolio - Joe Pris Calpito',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex flex-col overflow-x-hidden`}>
        <div className="flex-1 flex flex-col min-h-0">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
